// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhjfaudhaqczydjyzzgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoamZhdWRoYXFjenlkanl6emdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDMwODksImV4cCI6MjA3MDgxOTA4OX0.M2FuwogCE31y9ygP2z-9LfoVUTNua_HpaYVF5YSGYz4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});